version: '2'
services:
 web:
   build: .
   command: --url-alias /media /data
   ports:
    - "8000:80"
   depends_on:
    - db
 db:
   image: postgres
   environment:
    - POSTGRES_PASSWORD=postgres